version: '1.0.0'

services:
  backend:
    build: .
    container_name: backend-api
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mma
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
